name: ssd_keras

dependencies:
  - python=3.6
  - pip
  - pip:
          - beautifulsoup4
          - jupyter
          - keras
          - numpy
          - matplotlib
          - opencv-python
          - pandas
          - Pillow
          - tqdm
          - sklearn
          - tensorflow-gpu~=1.14.0
          # labelImg
          - labelImg
          # dev
          - pylint
          - black
          - flake8
          - rope
